### ISSUE TITLE
Fails to build on 32 bit architectures

### ISSUE THREAD

**Issue by iliastsi** [erikd/wide-word#86]
wide-word version 0.1.5.0 fails to build with GHC 9.4.6 on 32-bit architectures with the following error message:
```
src/Data/WideWord/Word64.hs:103:38: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word64#’
    • In the first argument of ‘wordToWord32#’, namely ‘c2’
      In the first argument of ‘W32#’, namely ‘(wordToWord32# c2)’
      In the second argument of ‘mkWord64’, namely
        ‘(W32# (wordToWord32# c2))’
    |
103 |     (mkWord64 0 (W32# (wordToWord32# c2)), mkWord64 (W32# (wordToWord32# s1)) (W32# (wordToWord32# s0)))
    |                                      ^^
```

For more information, see the full build log here https://buildd.debian.org/status/fetch.php?pkg=haskell-wide-word&arch=i386&ver=0.1.5.0-1&stamp=1693656322&raw=0.

**Comment by erikd** [comment]
Unfortunately, supporting 32 bit architectures is such a huge pain in the neck. On top of that, they tend to break for each new major release of the compiler. Even just testing on 32 bits is a pain in the neck.

Patches accepted, but I don't see myself finding the time to mess with this any time soon.
