### PR TITLE
Fix 32-bit support

### LINKED ISSUE #86: Fails to build on 32 bit architectures
wide-word version 0.1.5.0 fails to build with GHC 9.4.6 on 32-bit architectures with the following error message:
```
src/Data/WideWord/Word64.hs:103:38: error:
    • Couldn't match expected type ‘Word#’ with actual type ‘Word64#’
    • In the first argument of ‘wordToWord32#’, namely ‘c2’
      In the first argument of ‘W32#’, namely ‘(wordToWord32# c2)’
      In the second argument of ‘mkWord64’, namely
        ‘(W32# (wordToWord32# c2))’
    |
103 |     (mkWord64 0 (W32# (wordToWord32# c2)), mkWord64 (W32# (wordToWord32# s1)) (W32# (wordToWord32# s0)))
    |                                      ^^
```

For more information, see the full build log here https://buildd.debian.org/status/fetch.php?pkg=haskell-wide-word&arch=i386&ver=0.1.5.0-1&stamp=1693656322&raw=0.

### PR DESCRIPTION
**Pull request by Bodigrim**
Fixes #86, superseds #93 and #103.

It's a bit rough, but I guess better than broken.

### CODE REVIEW

**Review by erikd — APPROVED** [review]

**Comment by erikd** [comment]
Thanks for this. Maintaining 32 bit support is really painful, and I am sure this will not work for much more than 1 versions of GHC, but yes, rough is better than broken.
